#  飞书
APP_ID: cli_a4cc3568793a900e
APP_SECRET: A05Ot1vnraTmNNC48wB7eDNNJ7xtlZOB
APP_ENCRYPT_KEY: H1k7eEh4QOaRYDnKGbOSDcoPp6BTgmyC
APP_VERIFICATION_TOKEN: qcdNvnfw7eo6XDeZO78f475Mx6itu08j
# 请确保和飞书应用管理平台中的设置一致
BOT_NAME: chatGpt
# openAI key 支持负载均衡 可以填写多个key 用逗号分隔
OPENAI_KEY: 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,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,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
# 服务器配置
HTTP_PORT: 9000
HTTPS_PORT: 9001
USE_HTTPS: false
CERT_FILE: cert.pem
KEY_FILE: key.pem
# openai 地址, 一般不需要修改, 除非你有自己的反向代理
API_URL: https://api.openai.com
# 代理设置, 例如 "http://127.0.0.1:7890", ""代表不使用代理
HTTP_PROXY: ""

# AZURE OPENAI
AZURE_ON: false # set true to use Azure rather than OpenAI
AZURE_API_VERSION: 2023-03-15-preview # 2023-03-15-preview or 2022-12-01 refer https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference#completions
AZURE_RESOURCE_NAME: xxxx   # you can find in endpoint url. Usually looks like https://{RESOURCE_NAME}.openai.azure.com
AZURE_DEPLOYMENT_NAME: xxxx # usually looks like ...openai.azure.com/openai/deployments/{DEPLOYMENT_NAME}/chat/completions.
AZURE_OPENAI_TOKEN: xxxx  # Authentication key. We can use Azure Active Directory Authentication(TBD).

